config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :jets do
    resources :reviews
    resources :bookings, only: [:new, :create, :destroy]
  end
  resources :bookings, only: [:show, :destroy, :index]

  get '/my_jets', to: 'jets#my_jets'
  get '/dashboard', to: 'dashboard#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :jet

  validates :check_in, :check_out, presence: true
end

app/models/jet.rb
class Jet < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings , dependent: :destroy

  validates :name, :model, :jetType, :capacity, :price, :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_many_attached :photos

  JETTYPES = ["Turboprop Aircraft", "Helicopter", "Piston Aircraft", "Jet", "Light Jet", "Mid-Size Jet", "Federline Aircraft", "Short-Haul Aircraft", "Water Bomber", "Maritime Patrol"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :jet
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jets
  has_many :bookings
  has_many :owned_jets, class_name: 'Jet', foreign_key: :user_id
  has_many :jets, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    # @booking = Booking.find(params[:id])
    @booking = current_user.bookings.find(params[:id])
    #@booking = Booking.where(user_id: current_user.id).where(id: params[:id])
  end

  def new
    @booking = Booking.new
    @jet = Jet.find(params[:jet_id])
    @bookings_all = Booking.where(jet_id: @jet)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @jet = Jet.find(params[:jet_id])
    @booking.jet = @jet
    if @booking.save
      flash[:success] = "Booking was successfully created!"
      redirect_to jet_path(@jet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "Booking successfully deleted"
    redirect_to bookings_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def dashboard
    @jets = user_jets
    @bookings = user_bookings
  end

  private

  def user_jets
    @jets = Jet.where(user_id: current_user)
  end

  def user_bookings
    @bookings = Booking.where(user_id: current_user)
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController

  def index
    @jets = Jet.all
    if params[:price].present?
      sql_subquery = "price <= :price"
      @jets = @jets.where(sql_subquery, price: params[:price])
    end
    if params[:select_type].present?
      @jets = @jets.where(jetType: params[:select_type])
    end

    # if params[:query].present?
      # @jets = @jets.where("jetType ILIKE ?", "%#{params[:query]}%")
      # @jets = @jets.where(jetType: params[:query])
    @markers = @jets.geocoded.map do |jet|
      {
        lat: jet.latitude,
        lng: jet.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { jet: jet }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def my_jets
    @jets = current_user.owned_jets
  end

  def show
    @booking = Booking.new
    @jet = Jet.find(params[:id])
    @bookings_all = Booking.where(jet_id: @jet)
    @booking = Booking.new
    @markers = [{
      lat: @jet.latitude,
      lng: @jet.longitude,
      marker_html: render_to_string(partial: "marker")
      }]
  end

  def new
    @jet = Jet.new
  end

  def create
    @jet = Jet.new(jet_params)
    @jet.user = current_user
    if @jet.save
      redirect_to jet_path(@jet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @jet = Jet.find(params[:id])
  end

  def destroy
    @jet = Jet.find(params[:id])
    # Disassociate the jet from the user
    @jet.destroy
    flash[:notice] = "Jet successfully deleted"
    redirect_to jets_path
  end




  def update
    @jet = Jet.find(params[:id])
    @jet.update(jet_params)
    redirect_to jet_path(@jet)
  end

  private

  def jet_params
    params.require(:jet).permit(:name, :model, :capacity, :jetType, :location, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @jets = Jet.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
<h1>Bookings Details</h1>

<ul>
<% current_user.bookings.each do |book| %>
<div class="card">
<li><%= book.check_in %></li>
<li><%= book.check_out %></li>
<li><%= book.jet.name%></li>
<li><%= book.jet.price%></li>
<li><%= book.jet.location%></li>
<%= link_to "Cancel", booking_path(book), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<%= link_to "Show Details", booking_path(book) %>

<% end %>
</div>
</ul>
</div>

app/views/bookings/new.html.erb
<div class="container my-5 forms">
  <h1>Create a booking</h1>
  <div id="my-element" data-all-bookings = "<%= @bookings_all.to_json %>"></div>
  <%= simple_form_for([@jet, @booking]) do |f| %>
    <%= f.input :check_in,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :check_out,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "Submit", class: "button-form" %>
  <h1>test</h1>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
<h1>Booking Details</h1>

<ul>
<div class="card">
<li><%= @booking.user.first_name %></li>
<li><%= @booking.user.last_name %></li>
<li><%= @booking.check_in %></li>
<li><%= @booking.check_out %></li>
<li><%= @booking.jet.name%></li>
<li><%= @booking.jet.price%></li>
<li><%= @booking.jet.location%></li>
<%= link_to "Cancel", booking_path, data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>
</ul>
</div>

app/views/dashboard/dashboard.html.erb
<div class="container my-5 dashboard">
  <div class="container d-flex justify-content-between align-items-center mb-4">
    <div>
      <p style="font-size: 2rem;"><strong>Welcome</strong></p>
      <span style="font-size: 1.2rem;"><%= current_user.first_name.capitalize %></span>
      <span style="font-size: 1.2rem;"><%= current_user.last_name.capitalize %></span>
    </div>
    <h2>My Jets</h2>
    <%= link_to "Add a jet", new_jet_path, class: "btn rounded-3 button-form mb-4" %>
  </div>

  <div class="container d-flex flex-column justify-content-center align-items-center">
    <% @jets.each do |jet|  %>
      <div class="my-jets-container my-3">
        <div class="card card-user-jet">
          <div class="row g-0">
            <div class="col-md-4">
              <% photo = jet.photos.first %>
              <a href= <%= jet_path(jet) %> >
                <%= cl_image_tag photo.key %>
              </a>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <div class="container d-flex justify-content-between">
                  <h5 class="card-title"><%= jet.name  %></h5>
                  <div class="">
                    <a href= <%= edit_jet_path(jet) %> >
                      <div class="btn button-form">Edit</div>
                    </a>
                    <%# implement destroy button if the user are owner of this plane %>
                    <%= link_to "",
                      jet_path(jet),
                      data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},
                      class: "fa-solid fa-circle-xmark ms-3",
                      style: "color: #1B263B; text-decoration: none; font-size: 1.2rem;"
                    %>
                  </div>
                </div>
                <div class="container">
                  <p class="card-text"><strong>Model: </strong><%= jet.model %></p>
                  <p class="card-text"><strong>Location: </strong><%= jet.location %></p>
                  <p class="card-text"><strong>€ <%= jet.price %></strong> day</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="accordion">
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button button-acc" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Bookings
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <% jet.bookings.each do |jetbooking| %>
                  <div class="container py-3 border-bottom">
                    <p><strong>Booked by: </strong> <%= jetbooking.user.first_name.capitalize %></p>
                    <p><strong>Booked from: </strong> <%= jetbooking.check_in %> <strong> Booked to: </strong> <%= jetbooking.check_out %></p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="container d-flex justify-content-center mb-4 mt-5">
    <h2>My Bookings</h2>
  </div>

  <div class="container d-flex flex-column justify-content-center align-items-center">
    <% @bookings.each do |booking|  %>
      <div class="my-jets-container my-3">
        <div class="card card-user-jet">
          <div class="row g-0">
            <div class="col-md-4">
              <% photo = booking.jet.photos.first %>
              <%= cl_image_tag photo.key %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <div class="container d-flex justify-content-between">
                  <h5 class="card-title"><%= booking.jet.name  %></h5>
                  <%= link_to "",
                    booking_path(booking),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                    class: "fa-solid fa-circle-xmark",
                    style: "color: #1B263B; text-decoration: none; font-size: 1.2rem;"
                  %>
                </div>
                <div class="container d-flex justify-content-center align-items-center">
                  <div class="container">
                    <p class="card-text"><strong>Model: </strong><%= booking.jet.model %></p>
                    <p class="card-text"><strong>Location: </strong><%= booking.jet.location %></p>
                  </div>
                  <div class="container">
                    <p class="card-text"><strong>€ <%= booking.jet.price %></strong> day</p>
                    <p class="card-text"><strong>Check_in: </strong><%= booking.check_in %></p>
                    <p class="card-text"><strong>Check_out: </strong><%= booking.check_out %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/jets/_info_window.html.erb
<%# <div class="container b-5">
<%=link_to jet.name, jet_path(jet) %>
<%= cl_image_tag jet.photos[0].key, width: 120, height: 100, crop: :fill %>

<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('cl_image_tag jet.photos[0].key')">
    <%=link_to jet.name, jet_path(jet) %>
  </div>

</div>

app/views/jets/_marker.html.erb
<%= image_tag "plane-solid.svg", height: 20, width: 20, alt: "Logo" %>

app/views/jets/edit.html.erb
<div class="container my-5 forms">
  <h1>Edit the Jet</h1>

  <%= simple_form_for(@jet) do |f| %>
    <%= f.input :jetType, as: :select, collection: Jet::JETTYPES, prompt: 'Select Jet Type', label: false %>
    <%= f.input :name%>
    <%= f.input :model%>
    <%= f.input :capacity%>
    <%= f.input :price%>
    <%= f.input :location%>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Submit", class: "button-form" %>
  <% end %>
</div>

app/views/jets/index.html.erb
<div class="d-flex">

<div class="d-flex flex-column">
  <div class="container d-flex justify-content-center">
    <%= form_with url: jets_path, method: :get, class: "d-flex m-3" do %>
      <%= text_field_tag :price,
            params[:price],
            class: "form-control",
            placeholder: "Type a price"
        %>
      <%= submit_tag "Max price €", name: "", class: "btn button-form" %>
    <% end %>

    <%= form_with url: jets_path, method: :get, class: "d-flex m-3" do %>
      <%= select_tag :select_type, options_for_select(Jet::JETTYPES) %>
      <%= submit_tag "Jet type", name: "", class: "btn button-form" %>
    <% end %>
  </div>

  <div class="container">
    <div class="container grid-jets m-3">
      <% @jets.each do |jet| %>
        <div class="card border border-0 image-container" style="width: 20rem;">
          <div class="image-container">
              <div id="carouselExample" class="carousel slide">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <a href= <%= jet_path(jet) %> >
                      <% photo = jet.photos.first %> <!-- Select the first photo from the collection -->
                      <%= cl_image_tag photo.key, crop: :fill %>
                    </a>
                  </div>
                  <% if jet.photos[1] %>
                    <div class="carousel-item">
                      <% target_index = 1 %> <!-- Replace this with the index of the desired photo -->
                      <a href= <%= jet_path(jet) %> >
                        <% photo = jet.photos[1] %>
                        <%= cl_image_tag photo.key, crop: :fill %>
                      </a>
                    </div>
                  <% end %>
                  <% if jet.photos[2] %>
                    <div class="carousel-item">
                      <% target_index = 2 %> <!-- Replace this with the index of the desired photo -->
                      <a href= <%= jet_path(jet) %> >
                        <% photo = jet.photos[2] %>
                        <%= cl_image_tag photo.key, crop: :fill %>
                      </a>
                    </div>
                  <% end %>
                  <% if jet.photos[3] %>
                    <div class="carousel-item">
                      <% target_index = 3 %> <!-- Replace this with the index of the desired photo -->
                      <a href= <%= jet_path(jet) %> >
                        <% photo = jet.photos[3] %>
                        <%= cl_image_tag photo.key, crop: :fill %>
                      </a>
                    </div>
                  <% end %>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= jet.name %></h5>
            <p class="card-text"><strong>Model:</strong> <%= jet.model %></p>
            <p class="list-group-item" style="color: gray;"><strong>Location:</strong> <%= jet.location %></p>
            <p class="list-group-item" style="color: gray;"><strong>Type:</strong> <%= jet.jetType %></p>
            <p class="list-group-item mt-2"><strong>€ <%= jet.price %></strong> day</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div class="container map">
    <div style="width: 100%; height: 100vh; position: sticky; top: 0; margin-top: 1rem; margin-right: 1rem;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>

app/views/jets/my_jets.html.erb
<h1>My Jets</h1>

<ul>
<% @jets.each do |jet| %>
<li><%= jet.name %></li>
<% end %>
</ul>

app/views/jets/new.html.erb
<div class="container my-5 forms">
  <h1>Create a jet</h1>
  <%= simple_form_for(@jet) do |f| %>
    <%= f.input :jetType, as: :select, collection: Jet::JETTYPES, prompt: 'Select Jet Type', label: false %>
    <%= f.input :name%>
    <%= f.input :model%>
    <%= f.input :capacity%>
    <%= f.input :price%>
    <%= f.input :location%>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Submit", class: "button-form" %>
  <% end %>
</div>

app/views/jets/show.html.erb
<div class="flash-message-container" >
  <% if flash[:success] %>
    <div class="alert alert-primary">
      <%= flash[:success] %>
      <button type="button" class="btn-close" aria-label="Close"></button>
    </div>
  <% end %>
</div>

<div class="d-flex">
  <div class="container m-5 jet-title">
    <h1><%= @jet.name %></h1>
    <p><%= @jet.model %></p>

    <div class="jet-detail-image my-4">
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <% photo = @jet.photos.first %> <!-- Select the first photo from the collection -->
            <%= cl_image_tag photo.key, crop: :fill %>
          </div>
          <% if @jet.photos[1] %>
            <div class="carousel-item">
              <% target_index = 1 %> <!-- Replace this with the index of the desired photo -->
              <% photo = @jet.photos[1] %>
              <%= cl_image_tag photo.key, crop: :fill %>
            </div>
          <% end %>
          <% if @jet.photos[2] %>
            <div class="carousel-item">
              <% target_index = 2 %> <!-- Replace this with the index of the desired photo -->
              <% photo = @jet.photos[2] %>
              <%= cl_image_tag photo.key, crop: :fill %>
            </div>
          <% end %>
          <% if @jet.photos[3] %>
            <div class="carousel-item">
              <% target_index = 3 %> <!-- Replace this with the index of the desired photo -->
              <% photo = @jet.photos[3] %>
              <%= cl_image_tag photo.key, crop: :fill %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>

    <div class="d-flex justify-content-center text-center my-4">
      <div class="card rounded-4 mx-2 w-100 row align-items-center p-4 card-info">
        <i class="fa-solid fa-plane col" style="color: #1B263B;"></i>
        <p class="col"><strong>Jet Type</strong></p>
        <p class="col"><%= @jet.jetType %></p>
      </div>
      <div class="card rounded-4 mx-2 w-100 row align-items-center p-4 card-info">
        <i class="fa-solid fa-user-group col" style="color: #1B263B;"></i>
        <p class="col"><strong>Capacity</strong></p>
        <p class="col"><%= @jet.capacity %></p>
      </div>
      <div class="card rounded-4 mx-2 w-100 row align-items-center p-4 card-info">
        <i class="fa-solid fa-money-bill-wave col" style="color: #1B263B;"></i>
        <p class="col"><strong>Price</strong></p>
        <p class="col">€ <%= @jet.price %></p>
      </div>
      <div class="card rounded-4 mx-2 w-100 row align-items-center p-4 card-info">
        <i class="fa-solid fa-map-pin col" style="color: #1B263B;"></i>
        <p class="col"><strong>Location</strong></p>
        <p class="col"><%= @jet.location %></p>
      </div>
    </div>
    <%# implement destroy button if the user are owner of this plane %>


    <!--<%= link_to "Book your jet", new_jet_booking_path(@jet), class: "btn rounded-3 btn-primary" %>-->
    <div class="container">
      <% if @jet.user == current_user %>
        <%= link_to 'Add Photo', edit_jet_path(@jet), class: "btn button-form" %>
      <% end %>
    </div>
  </div>

  <div class="card rounded-5 card-details">
    <div style="width: 90%; height: 50vh; margin: 5%;"
    class="rounded-4"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div>
      <% if @jet.user != current_user %>
        <h4 class="ms-4 mb-0"><strong>Book this Jet</strong></h4>
        <div id="my-element" data-all-bookings = "<%= @bookings_all.to_json %>"></div>
        <div style="width: 90%; height: 50vh; margin: 5%;">
          <%= simple_form_for([@jet, @booking]) do |f| %>
              <%= f.input :check_in,
                          as: :string,
                          input_html: { data: { controller: "datepicker" } } %>
              <%= f.input :check_out,
                          as: :string,
                          input_html: { data: { controller: "datepicker" } } %>
              <%= f.submit "Book", class: "button-form"%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container d-flex justify-content-center">
    <p>© SkyRentalz GmbH</p>
    <p>Terms</p>
    <p>Sitemap</p>
    <p>Privacy</p>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex" do %>
      <%= image_tag "https://res.cloudinary.com/dgxfmpty5/image/upload/v1692710933/development/Untitled_design-2_njvcg4.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Jets", jets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign-up", new_user_registration_path, class: "btn button-nav mx-2" %>
          </li>
          <li class="nav-item dropdown">
            <%= content_tag :div, "Account", class: "dropdown-toggle btn button-nav mx-2", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end navbar-lewagon" aria-labelledby="navbarDropdown">
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkyRentalz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
      <%= render "layouts/navbar" %>
          <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render "layouts/footer" %>
  </body>
</html>